# This file is generated by device/htc/a16ul/setup-makefiles.sh

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/bin,system/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/etc,system/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/lib,system/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/usr,system/usr)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/vendor/bin,system/vendor/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/vendor/etc,system/vendor/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/vendor/firmware,system/vendor/firmware)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/vendor/lib,system/vendor/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/htc/a16ul/proprietary/vendor/thh,system/vendor/thh)
